/*
 * This source file was generated by the Gradle 'init' task
 */
package org.iskdevelop.mithra

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
